### ISSUE TITLE
打包出来的JS有些没经过Babel编译

### ISSUE THREAD

**Issue by cylhah** [zxpsuper/createVue#31]
自己写的src文件看起来是经过了babel编译，但是打包出来的vendor.js还有ES6的写法，比如说很多箭头函数，能让这些依赖已经过babel吗

**Comment by zxpsuper** [comment]
> 自己写的src文件看起来是经过了babel编译，但是打包出来的vendor.js还有ES6的写法，比如说很多箭头函数，能让这些依赖已经过babel吗

![image](https://user-images.githubusercontent.com/28730619/130910471-ff9e5aa5-1b23-48ab-886e-dc6b971428c0.png)
在build文件夹下的base配置中，默认是不编译 node_module文件夹下的文件，如果想要编译，直接删除exclude即可，但会增加编译时间
